#!/bin/bash
# ═══════════════════════════════════════════════════
#  ShadowLink — Server Deployment Script
#  Run this on your Oracle Cloud VPS (Ubuntu/Debian)
# ═══════════════════════════════════════════════════
#
# Usage:
#   chmod +x deploy-server.sh
#   sudo ./deploy-server.sh
#
# What this script does:
# 1. Creates /etc/shadowlink/ directory
# 2. Generates a self-signed TLS certificate
# 3. Sets up iptables rules (like your Oracle VCN setup)
# 4. Creates a systemd service (like xray.service)
# 5. Enables and starts the service

set -e

echo "╔══════════════════════════════════════════╗"
echo "║  ShadowLink — Server Deployment          ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# Check root
if [ "$EUID" -ne 0 ]; then
    echo "ERROR: Run as root (sudo ./deploy-server.sh)"
    exit 1
fi

# Create directories
echo "[1/6] Creating directories..."
mkdir -p /etc/shadowlink
mkdir -p /opt/shadowlink
mkdir -p /var/log/shadowlink

# Generate self-signed TLS certificate
echo "[2/6] Generating TLS certificate..."
if [ ! -f /etc/shadowlink/cert.pem ]; then
    openssl req -x509 -newkey rsa:2048 -sha256 \
        -days 3650 -nodes \
        -keyout /etc/shadowlink/key.pem \
        -out /etc/shadowlink/cert.pem \
        -subj "/CN=cloudsyncsolutions.com" \
        -addext "subjectAltName=DNS:cloudsyncsolutions.com,DNS:www.cloudsyncsolutions.com"
    
    chmod 600 /etc/shadowlink/key.pem
    chmod 644 /etc/shadowlink/cert.pem
    echo "  ✓ Self-signed cert generated (CN=cloudsyncsolutions.com)"
    echo "  TIP: For production, use Let's Encrypt with certbot for a real cert"
else
    echo "  ✓ Certificate already exists, skipping"
fi

# Setup iptables (equivalent to Oracle VCN ingress rules)
echo "[3/6] Configuring firewall (iptables)..."

# Flush existing rules
iptables -F INPUT 2>/dev/null || true

# Default policy: drop all incoming
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT ACCEPT

# Allow loopback
iptables -A INPUT -i lo -j ACCEPT

# Allow established connections
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

# Allow SSH (port 22) — management access
iptables -A INPUT -p tcp --dport 22 -j ACCEPT

# Allow HTTPS (port 443) — ShadowLink tunnel
iptables -A INPUT -p tcp --dport 443 -j ACCEPT

# Save iptables rules to persist across reboots
if command -v netfilter-persistent &> /dev/null; then
    netfilter-persistent save
elif command -v iptables-save &> /dev/null; then
    iptables-save > /etc/iptables/rules.v4 2>/dev/null || \
    iptables-save > /etc/iptables.rules 2>/dev/null || true
fi

echo "  ✓ Firewall configured:"
echo "    - Port 22 (SSH): OPEN"
echo "    - Port 443 (HTTPS/ShadowLink): OPEN"
echo "    - All other ports: BLOCKED"

# Create default server config
echo "[4/6] Creating server configuration..."
if [ ! -f /etc/shadowlink/config.toml ]; then
    cat > /etc/shadowlink/config.toml << 'TOML'
# ShadowLink Server Configuration
# ================================

# Listen on all interfaces, port 443 (standard HTTPS)
listen_addr = "0.0.0.0:443"

# TLS certificate (for HTTPS camouflage)
tls_cert_path = "/etc/shadowlink/cert.pem"
tls_key_path = "/etc/shadowlink/key.pem"

# Server identity key (generated by shadowlink-keygen)
server_key_path = "/etc/shadowlink/server.key.json"

# Add your client's public key here (from shadowlink-keygen output)
# You can add multiple clients
allowed_clients = [
    # "BASE64_CLIENT_PUBLIC_KEY_HERE",
]

# Set to false for maximum anonymity (no logs at all)
enable_logging = true

# Custom decoy website (optional)
# decoy_html_path = "/etc/shadowlink/decoy.html"

# DNS servers for resolving domains (server-side, prevents client DNS leaks)
dns_servers = ["1.1.1.1:53", "1.0.0.1:53", "8.8.8.8:53", "8.8.4.4:53"]
TOML
    echo "  ✓ Config created at /etc/shadowlink/config.toml"
else
    echo "  ✓ Config already exists, skipping"
fi

# Create systemd service (equivalent to xray.service)
echo "[5/6] Creating systemd service..."
cat > /etc/systemd/system/shadowlink.service << 'SERVICE'
[Unit]
Description=ShadowLink Secure Tunnel Server
After=network.target
Wants=network-online.target

[Service]
Type=simple
User=root
ExecStart=/opt/shadowlink/shadowlink-server /etc/shadowlink/config.toml
Restart=always
RestartSec=5
LimitNOFILE=65535

# Security hardening
NoNewPrivileges=yes
PrivateTmp=yes
ProtectSystem=strict
ProtectHome=yes
ReadWritePaths=/etc/shadowlink /var/log/shadowlink

# Passphrase via environment variable (set this!)
# EnvironmentFile=/etc/shadowlink/env
# Or set directly (less secure but simpler):
# Environment=SHADOWLINK_KEY_PASSPHRASE=your-passphrase-here

[Install]
WantedBy=multi-user.target
SERVICE

systemctl daemon-reload
echo "  ✓ Systemd service created: shadowlink.service"

# Summary
echo ""
echo "[6/6] Deployment preparation complete!"
echo ""
echo "═══════════════════════════════════════════════"
echo " NEXT STEPS:"
echo "═══════════════════════════════════════════════"
echo ""
echo " 1. On your Windows PC, run:"
echo "      shadowlink-keygen both"
echo ""
echo " 2. Copy the server key to your VPS:"
echo "      scp server.key.json root@your-vps:/etc/shadowlink/"
echo ""
echo " 3. Copy the server binary to your VPS:"
echo "      scp shadowlink-server root@your-vps:/opt/shadowlink/"
echo ""
echo " 4. Add your CLIENT public key to config:"
echo "      nano /etc/shadowlink/config.toml"
echo "      (paste key in allowed_clients list)"
echo ""
echo " 5. Set the passphrase:"
echo "      echo 'SHADOWLINK_KEY_PASSPHRASE=your-pass' > /etc/shadowlink/env"
echo "      chmod 600 /etc/shadowlink/env"
echo "      (uncomment EnvironmentFile in shadowlink.service)"
echo ""
echo " 6. Cross-compile for Linux on your Windows PC:"
echo "      rustup target add x86_64-unknown-linux-gnu"
echo "      cargo build --release --target x86_64-unknown-linux-gnu -p shadowlink-server"
echo ""
echo " 7. Start the server:"
echo "      systemctl enable shadowlink"
echo "      systemctl start shadowlink"
echo "      systemctl status shadowlink"
echo ""
echo " 8. On Oracle Cloud Dashboard:"
echo "      Ensure VCN ingress rules allow port 443 TCP"
echo ""
echo "═══════════════════════════════════════════════"
