[package]
name = "shadowlink-keygen"
version.workspace = true
edition.workspace = true

[[bin]]
name = "shadowlink-keygen"
path = "src/main.rs"

[dependencies]
shadowlink-core = { path = "../shadowlink-core" }
serde_json = { workspace = true }
anyhow = { workspace = true }
base64 = { workspace = true }
